using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Text;
using Marketplace.API.Data;
using Marketplace.API.Services;

var builder = WebApplication.CreateBuilder(args);

// Configure Kestrel to use PORT from environment (Render requirement)
var port = Environment.GetEnvironmentVariable("PORT") ?? "8080";
builder.WebHost.ConfigureKestrel(options =>
{
    options.ListenAnyIP(int.Parse(port));
});

// Add services to the container.
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// Database Configuration - Use Supabase PostgreSQL
var connectionString = builder.Configuration.GetConnectionString("MarketplaceDb") ?? "Host=db.iytscokxxuxprrivmzvg.supabase.co;Port=5432;Database=postgres;User Id=postgres;Password=PYvWmYoMYiO3RiCJ;Ssl Mode=Require;Trust Server Certificate=true";
builder.Services.AddDbContext<MarketplaceDbContext>(options =>
    options.UseNpgsql(connectionString));

// JWT Authentication
var jwtSettings = builder.Configuration.GetSection("JwtSettings");
var secretKey = jwtSettings["SecretKey"] ?? throw new InvalidOperationException("JWT SecretKey not configured");

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
.AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = jwtSettings["Issuer"],
        ValidAudience = jwtSettings["Audience"],
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(secretKey)),
        RoleClaimType = System.Security.Claims.ClaimTypes.Role
    };
    
    // Add detailed logging for authentication failures
    options.Events = new JwtBearerEvents
    {
        OnAuthenticationFailed = context =>
        {
            Console.WriteLine($"❌ JWT Authentication failed: {context.Exception.Message}");
            return Task.CompletedTask;
        },
        OnTokenValidated = context =>
        {
            var claims = context.Principal?.Claims.Select(c => $"{c.Type}: {c.Value}");
            Console.WriteLine($"✅ JWT Token validated. Claims: {string.Join(", ", claims ?? new[] { "none" })}");
            return Task.CompletedTask;
        },
        OnChallenge = context =>
        {
            Console.WriteLine($"⚠️ JWT Challenge: {context.Error}, {context.ErrorDescription}");
            return Task.CompletedTask;
        }
    };
});

// Custom Services
builder.Services.AddScoped<IProductService, ProductService>();
builder.Services.AddScoped<IPriceService, PriceService>();

// CORS - Allow frontend origins
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowFrontend", policy =>
    {
        policy.WithOrigins(
                "http://localhost:4200",
                "http://localhost:8100",
                "capacitor://localhost",
                "ionic://localhost",
                "http://localhost"
            )
            .AllowAnyMethod()
            .AllowAnyHeader()
            .AllowCredentials();
    });
    
    // Fallback policy for development
    options.AddPolicy("AllowAll", policy =>
    {
        policy.AllowAnyOrigin()
              .AllowAnyMethod()
              .AllowAnyHeader();
    });
});

var app = builder.Build();

// Apply migrations and seed data with error handling
try
{
    using (var scope = app.Services.CreateScope())
    {
        var context = scope.ServiceProvider.GetRequiredService<MarketplaceDbContext>();
        Console.WriteLine("📊 Ensuring Products table exists...");
        
        // Create Products table if it doesn't exist
        await context.Database.ExecuteSqlRawAsync(@"
            CREATE TABLE IF NOT EXISTS ""Products"" (
                ""Id"" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                ""VendorId"" TEXT NOT NULL,
                ""Name"" TEXT NOT NULL,
                ""Category"" TEXT NOT NULL,
                ""Description"" TEXT,
                ""Unit"" TEXT NOT NULL,
                ""CurrentPrice"" DECIMAL(18,2) NOT NULL,
                ""AvailableQuantity"" INTEGER NOT NULL,
                ""MinOrderQty"" INTEGER NOT NULL,
                ""ImageUrl"" TEXT,
                ""Grade"" TEXT,
                ""Emoji"" TEXT,
                ""IsActive"" BOOLEAN NOT NULL DEFAULT true,
                ""IsLive"" BOOLEAN NOT NULL DEFAULT false,
                ""MasterProductId"" UUID,
                ""PriceTiersJson"" TEXT,
                ""CreatedAt"" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                ""UpdatedAt"" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS ""IX_Products_VendorId"" ON ""Products""(""VendorId"");
            CREATE INDEX IF NOT EXISTS ""IX_Products_Category"" ON ""Products""(""Category"");
            CREATE INDEX IF NOT EXISTS ""IX_Products_IsLive"" ON ""Products""(""IsLive"");
            
            -- Add columns to existing table if they don't exist
            DO $$ 
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Products' AND column_name = 'IsLive') THEN
                    ALTER TABLE ""Products"" ADD COLUMN ""IsLive"" BOOLEAN NOT NULL DEFAULT false;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Products' AND column_name = 'MasterProductId') THEN
                    ALTER TABLE ""Products"" ADD COLUMN ""MasterProductId"" UUID;
                END IF;
            END $$;
        ");
        Console.WriteLine("✅ Products table ready");
        
        Console.WriteLine("🌱 Seeding mock data...");
        await DataSeeder.SeedMockDataAsync(context);
        Console.WriteLine("✅ Data seeded successfully");
    }
}
catch (Exception ex)
{
    Console.WriteLine($"⚠️ Database initialization failed: {ex.Message}");
    Console.WriteLine($"Stack trace: {ex.StackTrace}");
    Console.WriteLine("⚠️ Service will continue without seeded data");
}

// Configure the HTTP request pipeline.
// Enable Swagger in all environments
app.UseSwagger();
app.UseSwaggerUI();

// Disable HTTPS redirection when using Cloudflare Tunnel
// app.UseHttpsRedirection();
app.UseCors("AllowFrontend");
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();

app.Run();
